// <auto-generated />
using System;
using BlogDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogDAL.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogDAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrii",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mollis nunc. Mauris porta quis mauris at aliquam. Duis consectetur finibus ex id tempor. Etiam maximus enim et tortor scelerisque vestibulum. Sed viverra suscipit risus. Sed turpis risus, faucibus eu ultrices eu, facilisis ac diam. Donec molestie commodo sem hendrerit venenatis. Aliquam viverra orci sapien, sed ultrices tortor dapibus vel.Integer at dignissim erat, ac pulvinar turpis.Nullam tempus finibus quam at bibendum.Duis id risus velit. Cras ultrices, dui et vulputate egestas, sem eros dictum ligula, nec ultricies diam velit vel nisl. Cras rutrum ornare mauris id dignissim. Vivamus vel quam diam. Nulla nisl felis, euismod et cursus sit amet, tristique ac velit.Curabitur ac arcu convallis, dictum nunc a, consectetur neque. Pellentesque ipsum nunc, placerat eu dignissim et, pulvinar at metus.Morbi eget tristique elit,",
                            DatePosted = new DateTime(2022, 1, 22, 10, 11, 53, 930, DateTimeKind.Local).AddTicks(8646),
                            ImgDescription = "Img Description 1",
                            ImgPath = "https://picsum.photos/1000/800",
                            Subtitle = "Some subtitle1",
                            Title = "Some title1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrii",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mollis nunc. Mauris porta quis mauris at aliquam. Duis consectetur finibus ex id tempor. Etiam maximus enim et tortor scelerisque vestibulum. Sed viverra suscipit risus. Sed turpis risus, faucibus eu ultrices eu, facilisis ac diam. Donec molestie commodo sem hendrerit venenatis. Aliquam viverra orci sapien, sed ultrices tortor dapibus vel.Integer at dignissim erat, ac pulvinar turpis.Nullam tempus finibus quam at bibendum.Duis id risus velit. Cras ultrices, dui et vulputate egestas, sem eros dictum ligula, nec ultricies diam velit vel nisl. Cras rutrum ornare mauris id dignissim. Vivamus vel quam diam. Nulla nisl felis, euism",
                            DatePosted = new DateTime(2022, 1, 12, 10, 11, 53, 938, DateTimeKind.Local).AddTicks(9665),
                            ImgDescription = "Img Description 2",
                            ImgPath = "https://picsum.photos/1000/800",
                            Subtitle = "Some subtitle2",
                            Title = "Some title2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Andrii",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mollis nunc. Mauris porta quis mauris at aliquam. Duis consectetur finibus ex id tempor. Etiam maximus enim et tortor scelerisque vestibulum. Sed viverra suscipit risus. Sed turpis risus, faucibus eu ultrices eu, facilisis ac diam. Donec molestie commodo sem hendrerit venenatis. Aliquam viverra orci sapien, sed ultrices tortor dapibus vel.Integer at dignissim erat, ac pulvinar turpis.Nullam tempus finibus quam at bibendum.Duis id risus velit. Cras ultrices, dui et vulputate egestas, sem eros dictum ligula, nec ultricies diam velit vel nisl. Cras rutrum ornare mauris id dignissim. Vivamus vel quam diam. Nulla nisl felis, euismod et cursus sit amet, tristique ac velit.Curabitur ac arcu convallis, dictum nunc a, consectetur ne",
                            DatePosted = new DateTime(2022, 1, 31, 10, 11, 53, 938, DateTimeKind.Local).AddTicks(9776),
                            ImgDescription = "Img Description 3",
                            ImgPath = "https://picsum.photos/1000/800",
                            Subtitle = "Some subtitle3",
                            Title = "Some title3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Andrii",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mollis nunc. Mauris porta quis mauris at aliquam. Duis consectetur finibus ex id tempor. Etiam maximus enim et tortor scelerisque vestibulum. Sed viverra suscipit risus. Sed turpis risus, faucibus eu ultrices eu, facilisis ac diam. Donec molestie commodo sem hendrerit venenatis. Aliquam viverra orci sapien, sed ultrices tortor dapibus vel.Integer at dignissim erat, ac pulvinar turpis.Nullam tempus finibus quam at bibendum.Duis id risus velit. Cras ultrices, dui et vulputate egestas, sem eros dictum ligula, nec ultricies diam velit vel nisl. Cras rutrum ornare mauris id dignissim. Vivamus vel quam diam. Nulla nisl felis, euismod et cursus sit amet, tristique ac velit.Curabitur ac arcu convallis, dictum nunc a, consectetur neque. Pellentesque ipsum nunc, placerat eu dignissim et, pulvinar at metus.Morbi eget tristique elit, a maximus lacus.Praesent nibh massa, viverra sit amet mi vel, feugiat ultricies mi.Vivamus feugiat ",
                            DatePosted = new DateTime(2022, 1, 31, 10, 11, 53, 938, DateTimeKind.Local).AddTicks(9796),
                            ImgDescription = "Img Description 4",
                            ImgPath = "https://picsum.photos/1000/800",
                            Subtitle = "Some subtitle4",
                            Title = "Some title4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Andrii",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mollis nunc. Mauris porta quis mauris at aliquam. Duis consectetur finibus ex id tempor. Etiam maximus enim et tortor scelerisque vestibulum. Sed viverra suscipit risus. Sed turpis risus, faucibus eu ultrices eu, facilisis ac diam. Donec molestie commodo sem hendrerit venenatis. Aliquam viverra orci sapien, sed ultrices tortor dapibus vel.Integer at dignissim erat, ac pulvinar turpis.Nullam tempus finibus quam at bibendum.Duis id risus velit. Cras ultrices, dui et vulputate egestas, sem eros dictum ligula, nec ultricies diam velit vel nisl. Cras rutrum ornare mauris id dignissim. Vivamus vel quam diam. Nulla nisl felis, euismod et cursus sit amet, tristique ac velit.Curabitur ac arcu convallis, dictum nunc a, consectetur neque. Pellentesque ipsum nunc, placerat eu dignissim et, pulvinar at metus.Morbi eget tristique elit,",
                            DatePosted = new DateTime(2022, 1, 22, 10, 11, 53, 938, DateTimeKind.Local).AddTicks(9826),
                            ImgDescription = "Img Description 5",
                            ImgPath = "https://picsum.photos/1000/800",
                            Subtitle = "Some subtitle5",
                            Title = "Some title5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Andrii",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mollis nunc. Mauris porta quis mauris at aliquam. Duis consectetur finibus ex id tempor. Etiam maximus enim et tortor scelerisque vestibulum. Sed viverra suscipit risus. Sed turpis risus, faucibus eu ultrices eu, facilisis ac diam. Donec molestie commodo sem hendrerit venenatis. Aliquam viverra orci sapien, sed ultrices tortor dapibus vel.Integer at dignissim erat, ac pulvinar turpis.Nullam tempus finibus quam at bibendum.Duis id risus velit. Cras ultrices, dui et vulputate egestas, sem eros dictum ligula, nec ultricies diam velit vel nisl. Cras rutrum ornare mauris id dignissim. Vivamus vel quam diam. Nulla nisl felis, euismod et cursus sit amet, tristique ac velit.Curabitur ac arcu convallis, dictum nunc a, consectetur neque. Pellentesque ipsum nunc, placerat eu dignissim et, pulvinar at metus.Morbi eget tristique elit, a maximus lacus.Praesent nibh massa, viverra sit amet mi vel, feugiat ultricies mi.Vivamus feugiat",
                            DatePosted = new DateTime(2022, 1, 22, 10, 11, 53, 986, DateTimeKind.Local).AddTicks(8092),
                            ImgDescription = "Img Description 6",
                            ImgPath = "https://picsum.photos/1000/800",
                            Subtitle = "Some subtitle6",
                            Title = "Some title6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Andrii",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mollis nunc. Mauris porta quis mauris at aliquam. Duis consectetur finibus ex id tempor. Etiam maximus enim et tortor scelerisque vestibulum. Sed viverra suscipit risus. Sed turpis risus, faucibus eu ultrices eu, facilisis ac diam. Donec molestie commodo sem hendrerit venenatis. Aliquam viverra orci sapien, sed ultrices tortor dapibus vel.Integer at dignissim erat, ac pulvinar turpis.Nullam tempus finibus quam at bibendum.Duis id risus velit. Cras ultrices, dui et vulputate egestas, sem eros dictum ligula, nec ultricies diam velit vel nisl. Cras rutrum ornare mauris id dignissim. Vivamus vel quam diam. Nulla nisl felis, euismod et cursus sit amet, tristique ac velit.Curabitur ac arcu convallis, dictum nunc a, consectetur ne",
                            DatePosted = new DateTime(2021, 10, 24, 10, 11, 53, 986, DateTimeKind.Local).AddTicks(8190),
                            ImgDescription = "Img Description 7",
                            ImgPath = "https://picsum.photos/1000/800",
                            Subtitle = "Some subtitle7",
                            Title = "Some title7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
